### ISSUE TITLE
prismarine one ?

### ISSUE THREAD

**Issue by rom1504** [extremeheat/minecraft-inventory-gui#7]
what is https://github.com/PrismarineJS/prismarine-inventory-gui ?
where is this living ?

**Comment by extremeheat** [comment]
I believe @AwesomestCode forked the repo into that one

**Comment by extremeheat** [comment]
That repo can be moved into his github account and we can move this repo to the org if needed

**Comment by rom1504** [comment]
Completely up to you, I'm fine with both, but having a fork inside PrismarineJs that is not the upstream is confusing
Let's either delete the PrismarineJs fork or move this repo there

**Comment by rom1504** [comment]
solved
